name: Main-CI

# on: [push, pull_request]
on: 
  push:
    branchs:  
      - master
      - test
      - dev
  pull_request:
    branchs:  
      - master
      - test
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        GH_REF: ${{ secrets.GH_REF }}
        CO_REF: ${{ secrets.CO_REF }}
        BRANCH_NAME: ${{ github.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      run: |
        git clone -b `basename ${BRANCH_NAME}` ${CO_REF}
        bash ./tools/gitsync.sh pack 
        bash ./tools/gitsync.sh deploy mbfiles `basename ${BRANCH_NAME}` ${CO_REF}